FROM redmine:3.2-passenger




# ref https://github.com/docker-library/redmine/blob/master/3.2/passenger/Dockerfile

ENV REDMINE_INSTALL_DIR /usr/src/redmine

# RUN git clone https://github.com/rkallensee/redmine-google-analytics-plugin.git plugis/
CMD ["passenger", "start"]

