version: '2'

services:
  redmine:
    depends_on:
      - redmine_db
    build: .
    links:
      - redmine_db:postgres
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_PORT_5432_TCP=5432
      - POSTGRES_ENV_POSTGRES_USER=redmine
      - POSTGRES_ENV_POSTGRES_PASSWORD=secret
    volumes:
      - /data/redmine/files:/usr/src/redmine/files
      - /data/redmine/plugins:/usr/src/redmine/plugins
  redmine_db:
    image: postgres
    environment:
      - POSTGRES_USER=redmine
      - POSTGRES_PASSWORD=secret