version: '2'

services:
  redmine:
    image: redmine:4.1.1-passenger
    restart: always
    depends_on:
      - redmine_db
    links:
      - redmine_db:postgres
    environment:
      - REDMINE_DB_POSTGRES=redmine_db
      - REDMINE_DB_PORT=5432
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=secret
    ports:
      - "41001:3000"
    volumes:
      - "/c/mySpace/@DEVOPS/redmine_home/redmine/files:/usr/src/redmine/files"
      - "/c/mySpace/@DEVOPS/redmine_home/redmine/plugins:/usr/src/redmine/plugins"
      - "/c/mySpace/@DEVOPS/redmine_home/redmine/themes:/usr/src/redmine/themes"
  redmine_db:
    # ref: https://github.com/docker-library/docs/blob/master/postgres/README.md
    image: postgres:13
    # ref: https://hub.docker.com/_/postgres - Environment Variables
    environment:
      - POSTGRES_USER=redmine
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports: # HOST:CONTAINER
      - "41002:5432"
    volumes:
      - "/c/mySpace/@DEVOPS/redmine_home/db:/var/lib/postgresql/data"