version: '2'

services:
  jenkins:
    build: .
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - "/c/Users/netpyoung/@DEVOPS/jenkins_home:/var/jenkins_home"